# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

WORKDIR /app

# Copy package files and build source
COPY package.json package-lock.json tsconfig.json ./
COPY src/ ./src/

# Install dependencies and build
RUN npm install --ignore-scripts && npm run build

# Final command uses the built dist
CMD ["node", "dist/src/index.js"]
